task_name:    render-bot
max_workers:  30
world_module: src.worlds
overworld:    RenderOverworld

tasks:
  default:
    onboard_world:   RenderBotChatOnboardWorld
    task_world  :    RenderBotChatTaskWorld
    timeout:         1800
    agents_required: 1

opt:
  debug: True
  models:
    RenderBot:
      model: _custom/render
      Renderer:
        token: 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
        style: extroverted
        generation_config:
          model: text-ada-001
          top_p: 0.2
          max_tokens: 64
      Generator:
        model: transformer/generator
        model_file: zoo:blenderbot2/blenderbot2_400M/model
        interactive_mode: True
        doc_chunk_split_mode: word
        override:
          search_server: http://localhost:5000
          no_cuda: True
