task_name:    render-bot
max_workers:  30
world_module: src.worlds
overworld:    RenderOverworld

tasks:
  default:
    onboard_world:   RenderBotChatOnboardWorld
    task_world  :    RenderBotChatTaskWorld
    timeout:         1800
    agents_required: 1

opt:
  debug: True
  models:
    RenderBot:
      model: _render/gpt3
      gpt3:
        token: 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
        style: extroverted
        generation_config:
          model: text-ada-001  # "text-davinci-002"
          # top_p: 0.2
          max_tokens: 50
          temperature: 0
      generator:
        model: _custom/echo
