# -*- coding: utf-8 -*-
# =============================================================================
# Author: Yuxuan Wang
# Date: 12-06-2022
# =============================================================================
"""
Simply override the observe function to send FULL messages.
"""

import json
import asyncio

from parlai.chat_service.services.websocket.websocket_manager import WebsocketManager


class TerminalManager(WebsocketManager):
    """Chat Service manager that runs chat service tasks using terminal 
        to send and receive messages."""

    def observe_act(self, socket_id, act, quick_replies=None):
        """Override the observe_message function from the WebsocketManager
            in order to receive full message generated by the chatbot."""
            
        if quick_replies is not None:
            quick_replies = list(quick_replies)
        message = json.dumps(act)
        
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
        if socket_id not in self.subs:
            self.agent_id_to_overworld_future[socket_id].cancel()
        else:
            return loop.run_until_complete(self.subs[socket_id].write_message(message))

    def _create_agent(self, task_id, socketID):
        """Override the default method to create TerminalAgent instead 
            of WebsocketAgent."""
        
        from .agents import TerminalAgent
        
        return TerminalAgent(self.opt, self, socketID, task_id)
