# -*- coding: utf-8 -*-
# =============================================================================
# Author: Yuxuan Wang
# Date: 12-06-2022
# =============================================================================
"""
Simply override the observe function to send FULL messages.
"""

import logging

from parlai.chat_service.services.websocket.agents import WebsocketAgent


class TerminalAgent(WebsocketAgent):
    """Terminal agent that runs chat service tasks using terminal."""
    
    def observe(self, act):
        """Override the observe function from the WebsocketAgent
            in order to receive full message generated by the chatbot."""

        logging.info(f"Sending new message: {act}")
        
        quick_replies = act.get("quick_replies", None)
        if act.get("payload", None):
            self.manager.observe_payload(self.id, act["payload"], quick_replies)
        else:
            self.manager.observe_act(self.id, act, quick_replies)
